function Plot_signal(d1,e1,e2,e3,noise_type)
figure
subplot(4,1,1)
plot(d1)
title(['ECG Corrupted by ', noise_type],'FontSize',16,'FontWeight','bold')
xlabel('Samples (n)','FontSize',13,'FontWeight','bold')
ylabel('Amplitude (mV)','FontSize',13,'FontWeight','bold')
subplot(4,1,2)
plot(e1)
title('LMS Filter Response','FontSize',16,'FontWeight','bold')
xlabel('Samples (n)','FontSize',13,'FontWeight','bold')
ylabel('Amplitude (mV)','FontSize',13,'FontWeight','bold')
subplot(4,1,3)
plot(e2)
title('NLMS Filter Response','FontSize',16,'FontWeight','bold')
xlabel('Samples (n)','FontSize',13,'FontWeight','bold')
ylabel('Amplitude (mV)','FontSize',13,'FontWeight','bold')
subplot(4,1,4)
plot(e3)
title('RLS Filter Response','FontSize',16,'FontWeight','bold')
xlabel('Samples (n)','FontSize',13,'FontWeight','bold')
ylabel('Amplitude (mV)','FontSize',13,'FontWeight','bold')
end

